#!/usr/bin/expect -f
set timeout 60
spawn ssh -o StrictHostKeyChecking=no root@pve.dayamedialangit.co.id
expect "*?assword:*"
send "Alamatgue123\r"
expect "# "
send "pct exec 100 -- bash -c 'docker exec -i \$(docker ps -q --filter name=waha) curl -v http://172.17.0.1:9005'\r"
expect "# "
send "pct exec 100 -- bash -c 'docker exec -i \$(docker ps -q --filter name=waha) curl -I https://minio.dayamedialangit.co.id'\r"
expect "# "
send "exit\r"
